feat: add flex
TeamVastsea/QwQUI pull request #40
Opened 2024-10-07 07:17 UTC by LYXOfficial

2024-10-07 07:46 UTC, SnowballXueQiu approved these changes

2024-10-08 12:22 UTC, GaoNeng-wWw commented
Please run `pnpm changeset` generate changeset file

2024-10-08 12:24 UTC, GaoNeng-wWw requested changes

2024-10-08 12:24 UTC, GaoNeng-wWw commented on packages/components/flex/package.json
> +    "version": "1.0.1-alpha.0",
```suggestion
    "version": "0.0.0",
```

2024-10-08 12:24 UTC, GaoNeng-wWw commented on packages/components/flex/package.json
> +    "name": "@qwqui/center",
```suggestion
    "name": "@qwqui/flex",
```

2024-10-08 12:25 UTC, GaoNeng-wWw commented on packages/components/flex/src/flex.tsx
> +}
```suggestion
}
Flex.displayName='@qwqui/layout/flex'
```

2024-10-08 12:25 UTC, GaoNeng-wWw commented on packages/components/index.ts
Please do not push `index.ts` file

2024-10-08 12:29 UTC, GaoNeng-wWw commented
Please resolve change request before run `pnpm changeset` generate changeset file

2024-10-08 12:30 UTC, LYXOfficial commented
review大佬

2024-10-08 13:58 UTC, SnowballXueQiu commented
还有什么问题吗目前

2024-10-09 01:20 UTC, GaoNeng-wWw commented
请运行`pnpm changeset`来生成changeset文件

2024-10-09 05:00 UTC, GaoNeng-wWw approved these changes

2024-10-09 05:00 UTC, merged